version: '3'
services:
  app: &app_base
    build: .
    command: bin/rails s -p 3000 -b "0.0.0.0"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
  spring:
    <<: *app_base
    command: bin/spring server
    ports: []
volumes:
  bundle_cache:
